# general experiment and batch configs
data_directory: ${DATA_DIR}
save_dir: "model_save_large_lbls_flow_multibot_2"
batch_sizes: [4, 4, 4, 4]
robots: ['sawyer', 'franka', 'baxter', 'widowx'] 
max_steps: 600000
robots: ["sawyer"]

# loader_hparams used to initialize loader object
loader_hparams:
  load_T: 15
  
# model_hparams used to create graph and loss function
model_hparams:
  model: deterministic
  graph_type: vgg_conv
  tv_weight: 0
  lr: 0.0001
  context_frames: 5
  enc_filters: [512, 1024, 1536]
  lstm_filters: 1536
  dec_filters: [1024, 512]
  schedule_sampling_k: 4000
  img_flows: 32
  skip_flows: 16
