batch_size: 16
train_class: InverseTrainable 
max_steps: 200000


# list of dictionaries containing data sources along with filter parameters
batch_config:
  # selects sawyer data with autograsp enabled (adim=4, robot=sawyer)
  - data_directory: ${DATA_DIR}/hdf5
    robot: "sawyer"
    adim: 4

# loader_hparams used to initialize loader object
loader_hparams:
  dataset: "RoboNet"
  buffer_size: 10
  load_T: 4  #search/grid([2, 4, 11])
#  color_augmentation: 0.1
  img_size: [192, 256]

# model_hparams used to create graph and loss function
model_hparams:
  model: DiscretizedInverseModel
  graph_type: lstm_baseline
  vgg_path: ${VGG_DIR}
  context_actions: 2
  enc_dim: 256
  latent_dim: 64
  append_last_action: true
